### ISSUE TITLE
wxCocoaDialog as git submodule

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#1]
It may be worthwhile including wxCocoaDialog as an external, using a git submodule.

**Comment by tea** [comment]
I don't think so. You don't really need wxCocoaDialog code usually, just binary. This binary should probably be put into ebundles same way as Windows version is.

**Comment by bluemoon** [comment]
what about x86_32 and x86_64? there is 2 different architectures that you would have to have binaries for.

**Comment by adamv** [comment]
Nevermind.

**Comment by adamv** [comment]
Closing.
