### ISSUE TITLE
Different "close button" art for panels & tabs.

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#10]
Different close button graphics are used for the panels (bundle pane, project pane, search pane, etc.) and the editor tabs.

It's not bad per se that these graphics are different, but that they already look pretty similar and yet are different.

**Comment by astigsen** [comment]
These should definitely be unified to all using the same image.

**Comment by lexrupy** [comment]
In linux this should use the appropriate close image got from os

**Comment by adamv** [comment]
Closing.
