### ISSUE TITLE
Cannot make .deb

### ISSUE THREAD

**Issue by chanwit** [etexteditor/e#12]
I just run 'make deb' after I got an executable, and it failed.
Here's the message:

$ make deb
[TEST] ../external/stuff contents
make: **\* [.test-stuff] Error 1

**Comment by tea** [comment]
From linux-notes.txt:

== Bundling e into tar.gz, rpm or deb packages
1. Build e (release build) as described above
2. Checkout ebundles tree as described in http://code.google.com/p/ebundles/source/checkout
3. Export svn working tree into ./external/stuff (Bundles, Support and Themes directories must be present)
4. To create tar.gz archive run make -C src tar
5. To create RPM package run sudo make -C src rpm
6. To create Deb package run make -C src deb

You missed step 2 or step 3. Actually there should be one more step (3.5): build wxCocoaDialog and put it into external/Support/bin

**Comment by chanwit** [comment]
Thanks.
So it seems to be my misunderstanding. This issue shall be closed.
