### ISSUE TITLE
Bundling "Support" items

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#2]
Doing a build gets you the raw executable file, but the repository currently doesn't include any of the supporting files or default bundles that a packaged e download does.

If this is by intent (that is, you must get those files from a released e package), then a note to that effect should be added somewhere.

**Comment by tea** [comment]
Support files can be found at http://code.google.com/p/ebundles/, I believe these shouldn't be brought to E repository itself.
I'm not entirely sure if it is possible to keep one branch for Windows and Linux versions, or will have to branch Linux-specific.

**Comment by adamv** [comment]
Ok.

**Comment by adamv** [comment]
Closing.
