### ISSUE TITLE
Remove commented toolbar code?

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#20]
The codebase has lots of commented-out code to handle a toolbar. It's very likely that new work on the codebase will take this toolbar code further and further from being in a working state.

(A) Is it OK to start removing this dead code or (B) should it be considered a work-in-progress and re-enabled?

**Comment by astigsen** [comment]
It is very old code. It will be a good idea to remove it completely.

**Comment by adamv** [comment]
I've removed toolbar code that I've seen, and will remove anymore I run into.
