### ISSUE TITLE
Catalyst construtor creates UI elements, making it impossible to unittest several subsytems reliably.

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#41]
In order to unittest Document behavior, you need to create Catalyst objects first. However, when pointing Catalyst to a non-existing e.db, it will attempt to create a modal registration dialog.

In the unittest code, no actual eApp is created, and we don't want any UI to show anyway...so it is impossible to test any thing requiring Catalyst unless you point it at an existing registered e.db.

Using an existing e.db is possible, but not optimal, since it will put the unittest in an unknown starting state (ie, the state that you last left E in when used as an application.)

**Comment by adamv** [comment]
A possible solution would be to provide an "e.db" that is pre-registered, but with a test-only account, which is rejected when trying to run as a normal Windows GUI app.

**Comment by bluemoon** [comment]
yeah i noticed the same thing, if the catalyst functions were virtual you could over ride it with a derived class but either way something should be changed so that we can test it.

**Comment by astigsen** [comment]
It should only create the registration dlg if it cannot find a license file. Just creating a new db should be no problem.

**Comment by adamv** [comment]
Closing.

**Comment by adamv** [comment]
Closing.
