### ISSUE TITLE
Linux build expired??

### ISSUE THREAD

**Issue by rphl** [etexteditor/e#48]
Tried the Linux build .35 (http://e-texteditor.com/forum/viewtopic.php?p=13379#13379) . It reports that the trail period is expired, why? I think the Linux version is free?

**Comment by astigsen** [comment]
I assume that you just see this in the about box? The editor should still work just fine.

You can use the same license file on Linux as on Windows. But in the Linux version it will have no functional difference other than showing up in the about box (and give you a nice feeling of having supported the project :-)).

**Comment by rphl** [comment]
After closing the Editor the aboutbox popup AUTOMATICALLY with the 30days over expired warning. Just before 2 days installed.
A little bit annoying. I am linux only user.

**Comment by astigsen** [comment]
Thanks for the further detail. It should be fixed now: 7af2e4edbd347dd78eee28c3f47ed85acca31e97
