### ISSUE TITLE
What does freezing a document twice mean?

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#58]
Lots of methods in EditorCtrl seem to Freeze() a document at the top of some work and then again at the bottom of some work.

See EditorCtrl::SetBOM, for instance.

What does "Freezing" a document in, in this case?

**Comment by astigsen** [comment]
Freezing means marking this point as an undo point. Between two freezes you can do multible changes of the document which will then be collapsed into a single undo point.

Many commands do this to make their change a logical unit. There might be a previous function that has called freeze, but calling it multiple times has no effect, so they do it at top just to be sure.
