### ISSUE TITLE
C++ test frameworks?

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#7]
I'm a C# / Python programmer by day, and each of those platforms has some standard (unit) test harnesses (NUnit, xUnit, MSTest / unittest, doctest).

Anyone have any recommendations for C++ (unit) test frameworks? I'd like to start putting in place some tests, at least for the non-UI parts of the code. Of course I can just "write code" that does work and checks results, but something more organized than "a chunk of code" might be better in the long run.

**Comment by gavinheavyside** [comment]
I've tried a few, and have settled on CxxTest (http://cxxtest.tigris.org/).  It might take a little bit of effort to get it integrated into the build system, but unlike e.g. cppunit it doesn't have a separate library, so it can be integrated into a source tree without needing to be installed.

Other alternatives include Boost.Test (from http://www.boost.org/), and Google Test (http://code.google.com/p/googletest/).  Google Test integrates with Google Mock (http://code.google.com/p/googlemock/) which looks interesting, but I haven't tried it yet.

**Comment by adamv** [comment]
I've gone with Google Test, thanks.
