### ISSUE TITLE
get_externals_win.sh: line 38: mktemp: command not found

### ISSUE THREAD

**Issue by kristiannissen** [etexteditor/e#70]
I'm following the screen casts http://www.e-texteditor.com/forum/viewtopic.php?t=3570 for windows but after executing get_externals_win.sh I get the following: get_externals_win.sh: line 38: mktemp: command not found

I'm using windows xp professional version 2002 service pack 2

**Comment by adamv** [comment]
You need to install "mktemp" from the msys/mingw project.

**Comment by kristiannissen** [comment]
ok thank you
