### ISSUE TITLE
Remove BundleEditor & supporting code.

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#9]
"BundleEditor" has been deprecated in favor of "BundlePane"; BundleEditor and any support code used by it alone should be removed from the .vcproj and file system.

(Is there still code in BundleEditor that is pending to migrate into BundlePane?)

**Comment by astigsen** [comment]
I think it should be safe to remove all the old BundleEditor code.

**Comment by adamv** [comment]
This had been done (and merged upstream.)
